language: java
jdk:
  - oraclejdk7
  - oraclejdk8
  - openjdk7
before_install:
  - phantomjs_ver=2.1.1
  - curl -LO --retry 3 https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-${phantomjs_ver}-linux-x86_64.tar.bz2 && tar xvf phantomjs-${phantomjs_ver}-linux-x86_64.tar.bz2
  - export PATH="phantomjs-${phantomjs_ver}-linux-x86_64/bin:$PATH"
before_script:
  - "phantomjs --version"
install: /bin/true
script: mvn -U -DskipTests=false -Dtest.drivers=htmlunit,phantomjs clean test
sudo: false
